// <auto-generated />
using System;
using CloudM.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CloudM.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260313103247_AddAccountSettingsSoundEffects")]
    partial class AddAccountSettingsSoundEffects
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "unaccent");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CloudM.Domain.Entities.Account", b =>
                {
                    b.Property<Guid>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("CoverUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool?>("Gender")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastOnlineAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("AccountId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("FullName");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("FullName"), "GIN");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("FullName"), new[] { "gin_trgm_ops" });

                    b.HasIndex("RoleId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Accounts_Status");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("CloudM.Domain.Entities.AccountBlock", b =>
                {
                    b.Property<Guid>("BlockerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BlockedId")
                        .HasColumnType("uuid");

                    b.Property<string>("BlockedSnapshotUsername")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("BlockerSnapshotUsername")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("BlockerId", "BlockedId");

                    b.HasIndex("BlockedId", "CreatedAt")
                        .HasDatabaseName("IX_AccountBlocks_Blocked_CreatedAt");

                    b.HasIndex("BlockerId", "CreatedAt")
                        .HasDatabaseName("IX_AccountBlocks_Blocker_CreatedAt");

                    b.ToTable("AccountBlocks");
                });

            modelBuilder.Entity("CloudM.Domain.Entities.AccountSearchHistory", b =>
                {
                    b.Property<Guid>("CurrentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastSearchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CurrentId", "TargetId");

                    b.HasIndex("TargetId");

                    b.HasIndex("CurrentId", "LastSearchedAt")
                        .HasDatabaseName("IX_AccountSearchHistories_Current_LastSearchedAt");

                    b.ToTable("AccountSearchHistories");
                });

            modelBuilder.Entity("CloudM.Domain.Entities.AccountSettings", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<int>("AddressPrivacy")
                        .HasColumnType("integer");

                    b.Property<int>("DefaultPostPrivacy")
                        .HasColumnType("integer");

                    b.Property<int>("FollowPrivacy")
                        .HasColumnType("integer");

                    b.Property<int>("FollowerPrivacy")
                        .HasColumnType("integer");

                    b.Property<int>("FollowingPrivacy")
                        .HasColumnType("integer");

                    b.Property<int>("GroupChatInvitePermission")
                        .HasColumnType("integer");

                    b.Property<string>("Language")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("OnlineStatusVisibility")
                        .HasColumnType("integer");

                    b.Property<int>("PhonePrivacy")
                        .HasColumnType("integer");

                    b.Property<bool>("SoundEffectsEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("StoryHighlightPrivacy")
                        .HasColumnType("integer");

                    b.Property<int>("TagPermission")
                        .HasColumnType("integer");

                    b.HasKey("AccountId");

                    b.ToTable("AccountSettings");
                });

            modelBuilder.Entity("CloudM.Domain.Entities.Comment", b =>
                {
                    b.Property<Guid>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ParentCommentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CommentId");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("IX_Comment_AccountId");

                    b.HasIndex("AccountId", "CreatedAt", "PostId")
                        .HasDatabaseName("IX_Comment_Account_CreatedAt_PostId");

                    b.HasIndex("ParentCommentId", "CreatedAt", "CommentId")
                        .HasDatabaseName("IX_Comment_Parent_Created");

                    b.HasIndex("PostId", "AccountId", "CreatedAt")
                        .HasDatabaseName("IX_Comment_Post_Account_Created");

                    b.HasIndex("PostId", "ParentCommentId", "CreatedAt", "CommentId")
                        .HasDatabaseName("IX_Comment_Post_Parent_Created");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("CloudM.Domain.Entities.CommentReact", b =>
                {
                    b.Property<Guid>("CommentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ReactType")
                        .HasColumnType("integer");

                    b.HasKey("CommentId", "AccountId");

                    b.HasIndex("AccountId");

                    b.ToTable("CommentReacts");
                });

            modelBuilder.Entity("CloudM.Domain.Entities.Conversation", b =>
                {
                    b.Property<Guid>("ConversationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConversationAvatar")
                        .HasColumnType("text");

                    b.Property<string>("ConversationName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsGroup")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("Owner")
                        .HasColumnType("uuid");

                    b.Property<string>("Theme")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("ConversationId");

                    b.HasIndex("ConversationName")
                        .HasDatabaseName("IX_Conversations_Name_Trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("ConversationName"), "GIN");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("ConversationName"), new[] { "gin_trgm_ops" });

                    b.HasIndex("CreatedBy");

                    b.HasIndex("Owner");

                    b.ToTable("Conversations", t =>
                        {
                            t.HasCheckConstraint("CK_Conversations_GroupOwner", "(\"IsGroup\" = FALSE AND \"Owner\" IS NULL) OR (\"IsGroup\" = TRUE AND \"Owner\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("CloudM.Domain.Entities.ConversationMember", b =>
                {
                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ClearedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("HasLeft")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMuted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastSeenMessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nickname")
                        .HasColumnType("text");

                    b.HasKey("ConversationId", "AccountId");

                    b.HasIndex("AccountId");

                    b.HasIndex("ConversationId", "HasLeft", "AccountId")
                        .HasDatabaseName("IX_ConversationMember_Conversation_HasLeft_Account");

                    b.HasIndex("AccountId", "HasLeft", "IsMuted", "ConversationId")
                        .HasDatabaseName("IX_ConversationMember_Account_State_Conversation");

                    b.ToTable("ConversationMembers");
                });

            modelBuilder.Entity("CloudM.Domain.Entities.EmailVerification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CodeSalt")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DailySendCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DailyWindowStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("ExpiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastSentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SendCountInWindow")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SendWindowStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_EmailVerifications_Email_Unique");

                    b.HasIndex("ExpiredAt")
                        .HasDatabaseName("IX_EmailVerifications_ExpiredAt");

                    b.ToTable("EmailVerifications");
                });

            modelBuilder.Entity("CloudM.Domain.Entities.ExternalLogin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Provider")
                        .HasColumnType("integer");

                    b.Property<string>("ProviderUserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "Provider")
                        .IsUnique()
                        .HasDatabaseName("IX_ExternalLogins_AccountId_Provider_Unique");

                    b.HasIndex("Provider", "ProviderUserId")
                        .IsUnique()
                        .HasDatabaseName("IX_ExternalLogins_Provider_ProviderUserId_Unique");

                    b.ToTable("ExternalLogins");
                });

            modelBuilder.Entity("CloudM.Domain.Entities.Follow", b =>
                {
                    b.Property<Guid>("FollowerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FollowedId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("FollowerId", "FollowedId");

                    b.HasIndex("FollowedId", "CreatedAt");

                    b.HasIndex("FollowerId", "CreatedAt");

                    b.ToTable("Follows");
                });

            modelBuilder.Entity("CloudM.Domain.Entities.FollowRequest", b =>
                {
                    b.Property<Guid>("RequesterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RequesterId", "TargetId");

                    b.HasIndex("RequesterId", "CreatedAt");

                    b.HasIndex("TargetId", "CreatedAt");

                    b.ToTable("FollowRequests");
                });

            modelBuilder.Entity("CloudM.Domain.Entities.Message", b =>
                {
                    b.Property<Guid>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRecalled")
                        .HasColumnType("boolean");

                    b.Property<int>("MessageType")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("RecalledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReplyToMessageId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SystemMessageDataJson")
                        .HasColumnType("text");

                    b.HasKey("MessageId");

                    b.HasIndex("AccountId");

                    b.HasIndex("ReplyToMessageId");

                    b.HasIndex("ConversationId", "AccountId", "SentAt")
                        .HasDatabaseName("IX_Message_Conversation_Account_SentAt");

                    b.HasIndex("ConversationId", "SentAt", "MessageId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("CloudM.Domain.Entities.MessageHidden", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("HiddenAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MessageId", "AccountId");

                    b.HasIndex("AccountId");

                    b.ToTable("MessageHiddens");
                });

            modelBuilder.Entity("CloudM.Domain.Entities.MessageMedia", b =>
                {
                    b.Property<Guid>("MessageMediaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .HasColumnType("text");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<int>("MediaType")
                        .HasColumnType("integer");

                    b.Property<string>("MediaUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("text");

                    b.HasKey("MessageMediaId");

                    b.HasIndex("MessageId");

                    b.HasIndex("MediaType", "CreatedAt", "MessageId")
                        .HasDatabaseName("IX_MessageMedia_Type_Created_Message");

                    b.ToTable("MessageMedias");
                });

            modelBuilder.Entity("CloudM.Domain.Entities.MessageReact", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ReactType")
                        .HasColumnType("integer");

                    b.HasKey("MessageId", "AccountId");

                    b.HasIndex("AccountId");

                    b.HasIndex("MessageId", "ReactType")
                        .HasDatabaseName("IX_MessageReacts_MessageId_ReactType");

                    b.ToTable("MessageReacts");
                });

            modelBuilder.Entity("CloudM.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ActorCount")
                        .HasColumnType("integer");

                    b.Property<string>("AggregateKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EventCount")
                        .HasColumnType("integer");

                    b.Property<Guid?>("LastActorId")
                        .HasColumnType("uuid");

                    b.Property<string>("LastActorSnapshot")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("LastEventAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid>("RecipientId")
                        .HasColumnType("uuid");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TargetId")
                        .HasColumnType("uuid");

                    b.Property<int>("TargetKind")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("NotificationId");

                    b.HasIndex("RecipientId", "LastEventAt", "NotificationId")
                        .HasDatabaseName("IX_Notifications_Recipient_LastEventAt_NotificationId");

                    b.HasIndex("RecipientId", "Type", "AggregateKey")
                        .IsUnique()
                        .HasDatabaseName("IX_Notifications_Recipient_Type_Aggregate_Unique");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("CloudM.Domain.Entities.NotificationContribution", b =>
                {
                    b.Property<Guid>("ContributionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("NotificationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<int>("SourceType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ContributionId");

                    b.HasIndex("ActorId");

                    b.HasIndex("NotificationId", "IsActive", "UpdatedAt")
                        .HasDatabaseName("IX_NotificationContributions_Notification_IsActive_UpdatedAt");

                    b.HasIndex("NotificationId", "SourceType", "SourceId")
                        .IsUnique()
                        .HasDatabaseName("IX_NotificationContributions_Notification_Source_Unique");

                    b.ToTable("NotificationContributions");
                });

            modelBuilder.Entity("CloudM.Domain.Entities.NotificationOutbox", b =>
                {
                    b.Property<Guid>("OutboxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NextRetryAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RecipientId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("OutboxId");

                    b.HasIndex("RecipientId");

                    b.HasIndex("LockedUntil", "Status")
                        .HasDatabaseName("IX_NotificationOutbox_LockedUntil_Status");

                    b.HasIndex("Status", "NextRetryAt", "OccurredAt")
                        .HasDatabaseName("IX_NotificationOutbox_Status_NextRetryAt_OccurredAt");

                    b.ToTable("NotificationOutboxes");
                });

            modelBuilder.Entity("CloudM.Domain.Entities.NotificationReadState", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastFollowRequestsSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastNotificationsSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AccountId");

                    b.ToTable("NotificationReadStates");
                });

            modelBuilder.Entity("CloudM.Domain.Entities.PinnedMessage", b =>
                {
                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("PinnedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PinnedBy")
                        .HasColumnType("uuid");

                    b.HasKey("ConversationId", "MessageId");

                    b.HasIndex("MessageId");

                    b.HasIndex("PinnedBy");

                    b.HasIndex("ConversationId", "PinnedAt")
                        .HasDatabaseName("IX_PinnedMessage_Conversation_PinnedAt");

                    b.ToTable("PinnedMessages");
                });

            modelBuilder.Entity("CloudM.Domain.Entities.Post", b =>
                {
                    b.Property<Guid>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FeedAspectRatio")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("PostCode")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<int>("Privacy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PostId");

                    b.HasIndex("PostCode")
                        .IsUnique();

                    b.HasIndex("AccountId", "IsDeleted", "CreatedAt", "PostId")
                        .HasDatabaseName("IX_Posts_Account_CreatedAt_PostId");

                    b.HasIndex("IsDeleted", "Privacy", "CreatedAt", "PostId")
                        .HasDatabaseName("IX_Posts_Feed");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("CloudM.Domain.Entities.PostMedia", b =>
                {
                    b.Property<Guid>("MediaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MediaUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("MediaId");

                    b.HasIndex("PostId");

                    b.ToTable("PostMedias");
                });

            modelBuilder.Entity("CloudM.Domain.Entities.PostReact", b =>
                {
                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ReactType")
                        .HasColumnType("integer");

                    b.HasKey("PostId", "AccountId");

                    b.HasIndex("PostId", "CreatedAt")
                        .HasDatabaseName("IX_PostReacts_Post_CreatedAt");

                    b.HasIndex("AccountId", "CreatedAt", "PostId")
                        .HasDatabaseName("IX_PostReacts_Account_CreatedAt_PostId");

                    b.ToTable("PostReacts");
                });

            modelBuilder.Entity("CloudM.Domain.Entities.PostSave", b =>
                {
                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PostId", "AccountId");

                    b.HasIndex("AccountId", "CreatedAt", "PostId")
                        .HasDatabaseName("IX_PostSaves_Account_CreatedAt");

                    b.ToTable("PostSaves");
                });

            modelBuilder.Entity("CloudM.Domain.Entities.PostTag", b =>
                {
                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TaggedAccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PostId", "TaggedAccountId");

                    b.HasIndex("TaggedAccountId", "CreatedAt")
                        .HasDatabaseName("IX_PostTags_TaggedAccount_CreatedAt");

                    b.ToTable("PostTags");
                });

            modelBuilder.Entity("CloudM.Domain.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("CloudM.Domain.Entities.Story", b =>
                {
                    b.Property<Guid>("StoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("BackgroundColorKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ContentType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FontSizeKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FontTextKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MediaUrl")
                        .HasColumnType("text");

                    b.Property<int>("Privacy")
                        .HasColumnType("integer");

                    b.Property<string>("TextColorKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TextContent")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("StoryId");

                    b.HasIndex("AccountId", "CreatedAt")
                        .HasDatabaseName("IX_Stories_Account_Created");

                    b.HasIndex("IsDeleted", "ExpiresAt", "CreatedAt")
                        .HasDatabaseName("IX_Stories_Active");

                    b.HasIndex("Privacy", "ExpiresAt", "CreatedAt")
                        .HasDatabaseName("IX_Stories_Privacy_Active")
                        .HasFilter("\"IsDeleted\" = FALSE");

                    b.HasIndex("AccountId", "IsDeleted", "ExpiresAt", "CreatedAt")
                        .HasDatabaseName("IX_Stories_Account_Archive");

                    b.ToTable("Stories", t =>
                        {
                            t.HasCheckConstraint("CK_Stories_ContentPayload", "((\"ContentType\" IN (0,1) AND \"MediaUrl\" IS NOT NULL AND \"TextContent\" IS NULL AND \"FontTextKey\" IS NULL AND \"FontSizeKey\" IS NULL AND \"TextColorKey\" IS NULL) OR (\"ContentType\" = 2 AND \"TextContent\" IS NOT NULL AND length(btrim(\"TextContent\")) > 0 AND \"MediaUrl\" IS NULL))");

                            t.HasCheckConstraint("CK_Stories_ExpiresAt", "\"ExpiresAt\" > \"CreatedAt\"");
                        });
                });

            modelBuilder.Entity("CloudM.Domain.Entities.StoryHighlightGroup", b =>
                {
                    b.Property<Guid>("StoryHighlightGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("StoryHighlightGroupId");

                    b.HasIndex("AccountId", "CreatedAt")
                        .HasDatabaseName("IX_StoryHighlightGroups_Account_CreatedAt");

                    b.ToTable("StoryHighlightGroups", t =>
                        {
                            t.HasCheckConstraint("CK_StoryHighlightGroups_Name_NotEmpty", "length(btrim(\"Name\")) > 0");
                        });
                });

            modelBuilder.Entity("CloudM.Domain.Entities.StoryHighlightItem", b =>
                {
                    b.Property<Guid>("StoryHighlightGroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("StoryHighlightGroupId", "StoryId");

                    b.HasIndex("StoryId")
                        .HasDatabaseName("IX_StoryHighlightItems_StoryId");

                    b.HasIndex("StoryHighlightGroupId", "AddedAt")
                        .HasDatabaseName("IX_StoryHighlightItems_Group_AddedAt");

                    b.ToTable("StoryHighlightItems");
                });

            modelBuilder.Entity("CloudM.Domain.Entities.StoryView", b =>
                {
                    b.Property<Guid>("StoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ViewerAccountId")
                        .HasColumnType("uuid");

                    b.Property<int?>("ReactType")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ReactedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ViewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("StoryId", "ViewerAccountId");

                    b.HasIndex("StoryId", "ReactType")
                        .HasDatabaseName("IX_StoryViews_Story_ReactType");

                    b.HasIndex("StoryId", "ViewedAt")
                        .HasDatabaseName("IX_StoryViews_Story_ViewedAt");

                    b.HasIndex("ViewerAccountId", "StoryId")
                        .HasDatabaseName("IX_StoryViews_Viewer_Story");

                    b.HasIndex("ViewerAccountId", "ViewedAt")
                        .HasDatabaseName("IX_StoryViews_Viewer_ViewedAt");

                    b.ToTable("StoryViews", t =>
                        {
                            t.HasCheckConstraint("CK_StoryViews_ReactPair", "((\"ReactType\" IS NULL AND \"ReactedAt\" IS NULL) OR (\"ReactType\" IS NOT NULL AND \"ReactedAt\" IS NOT NULL))");
                        });
                });

            modelBuilder.Entity("CloudM.Domain.Entities.Account", b =>
                {
                    b.HasOne("CloudM.Domain.Entities.Role", "Role")
                        .WithMany("Accounts")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CloudM.Domain.Entities.AccountBlock", b =>
                {
                    b.HasOne("CloudM.Domain.Entities.Account", "Blocked")
                        .WithMany("BlocksReceived")
                        .HasForeignKey("BlockedId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CloudM.Domain.Entities.Account", "Blocker")
                        .WithMany("BlocksInitiated")
                        .HasForeignKey("BlockerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Blocked");

                    b.Navigation("Blocker");
                });

            modelBuilder.Entity("CloudM.Domain.Entities.AccountSearchHistory", b =>
                {
                    b.HasOne("CloudM.Domain.Entities.Account", "Current")
                        .WithMany()
                        .HasForeignKey("CurrentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CloudM.Domain.Entities.Account", "Target")
                        .WithMany()
                        .HasForeignKey("TargetId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Current");

                    b.Navigation("Target");
                });

            modelBuilder.Entity("CloudM.Domain.Entities.AccountSettings", b =>
                {
                    b.HasOne("CloudM.Domain.Entities.Account", "Account")
                        .WithOne("Settings")
                        .HasForeignKey("CloudM.Domain.Entities.AccountSettings", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("CloudM.Domain.Entities.Comment", b =>
                {
                    b.HasOne("CloudM.Domain.Entities.Account", "Account")
                        .WithMany("Comments")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CloudM.Domain.Entities.Comment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CloudM.Domain.Entities.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("ParentComment");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("CloudM.Domain.Entities.CommentReact", b =>
                {
                    b.HasOne("CloudM.Domain.Entities.Account", "Account")
                        .WithMany("CommentReacts")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CloudM.Domain.Entities.Comment", "Comment")
                        .WithMany("CommentReacts")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Comment");
                });

            modelBuilder.Entity("CloudM.Domain.Entities.Conversation", b =>
                {
                    b.HasOne("CloudM.Domain.Entities.Account", "CreatedByAccount")
                        .WithMany("CreatedConversations")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CloudM.Domain.Entities.Account", "OwnerAccount")
                        .WithMany("OwnedConversations")
                        .HasForeignKey("Owner")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByAccount");

                    b.Navigation("OwnerAccount");
                });

            modelBuilder.Entity("CloudM.Domain.Entities.ConversationMember", b =>
                {
                    b.HasOne("CloudM.Domain.Entities.Account", "Account")
                        .WithMany("Conversations")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CloudM.Domain.Entities.Conversation", "Conversation")
                        .WithMany("Members")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("CloudM.Domain.Entities.ExternalLogin", b =>
                {
                    b.HasOne("CloudM.Domain.Entities.Account", "Account")
                        .WithMany("ExternalLogins")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("CloudM.Domain.Entities.Follow", b =>
                {
                    b.HasOne("CloudM.Domain.Entities.Account", "Followed")
                        .WithMany("Followers")
                        .HasForeignKey("FollowedId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CloudM.Domain.Entities.Account", "Follower")
                        .WithMany("Followings")
                        .HasForeignKey("FollowerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Followed");

                    b.Navigation("Follower");
                });

            modelBuilder.Entity("CloudM.Domain.Entities.FollowRequest", b =>
                {
                    b.HasOne("CloudM.Domain.Entities.Account", "Requester")
                        .WithMany("FollowRequestsSent")
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CloudM.Domain.Entities.Account", "Target")
                        .WithMany("FollowRequestsReceived")
                        .HasForeignKey("TargetId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Requester");

                    b.Navigation("Target");
                });

            modelBuilder.Entity("CloudM.Domain.Entities.Message", b =>
                {
                    b.HasOne("CloudM.Domain.Entities.Account", "Account")
                        .WithMany("Messages")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CloudM.Domain.Entities.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CloudM.Domain.Entities.Message", "ReplyToMessage")
                        .WithMany()
                        .HasForeignKey("ReplyToMessageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Account");

                    b.Navigation("Conversation");

                    b.Navigation("ReplyToMessage");
                });

            modelBuilder.Entity("CloudM.Domain.Entities.MessageHidden", b =>
                {
                    b.HasOne("CloudM.Domain.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CloudM.Domain.Entities.Message", "Message")
                        .WithMany("HiddenBy")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Message");
                });

            modelBuilder.Entity("CloudM.Domain.Entities.MessageMedia", b =>
                {
                    b.HasOne("CloudM.Domain.Entities.Message", "Message")
                        .WithMany("Medias")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("CloudM.Domain.Entities.MessageReact", b =>
                {
                    b.HasOne("CloudM.Domain.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CloudM.Domain.Entities.Message", "Message")
                        .WithMany("Reacts")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Message");
                });

            modelBuilder.Entity("CloudM.Domain.Entities.Notification", b =>
                {
                    b.HasOne("CloudM.Domain.Entities.Account", "Recipient")
                        .WithMany()
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipient");
                });

            modelBuilder.Entity("CloudM.Domain.Entities.NotificationContribution", b =>
                {
                    b.HasOne("CloudM.Domain.Entities.Account", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CloudM.Domain.Entities.Notification", "Notification")
                        .WithMany("Contributions")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Notification");
                });

            modelBuilder.Entity("CloudM.Domain.Entities.NotificationOutbox", b =>
                {
                    b.HasOne("CloudM.Domain.Entities.Account", "Recipient")
                        .WithMany()
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipient");
                });

            modelBuilder.Entity("CloudM.Domain.Entities.NotificationReadState", b =>
                {
                    b.HasOne("CloudM.Domain.Entities.Account", "Account")
                        .WithOne("NotificationReadState")
                        .HasForeignKey("CloudM.Domain.Entities.NotificationReadState", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("CloudM.Domain.Entities.PinnedMessage", b =>
                {
                    b.HasOne("CloudM.Domain.Entities.Conversation", "Conversation")
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CloudM.Domain.Entities.Message", "Message")
                        .WithMany()
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CloudM.Domain.Entities.Account", "PinnedByAccount")
                        .WithMany()
                        .HasForeignKey("PinnedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("Message");

                    b.Navigation("PinnedByAccount");
                });

            modelBuilder.Entity("CloudM.Domain.Entities.Post", b =>
                {
                    b.HasOne("CloudM.Domain.Entities.Account", "Account")
                        .WithMany("Posts")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("CloudM.Domain.Entities.PostMedia", b =>
                {
                    b.HasOne("CloudM.Domain.Entities.Post", "Post")
                        .WithMany("Medias")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("CloudM.Domain.Entities.PostReact", b =>
                {
                    b.HasOne("CloudM.Domain.Entities.Account", "Account")
                        .WithMany("PostReacts")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CloudM.Domain.Entities.Post", "Post")
                        .WithMany("Reacts")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("CloudM.Domain.Entities.PostSave", b =>
                {
                    b.HasOne("CloudM.Domain.Entities.Account", "Account")
                        .WithMany("PostSaves")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CloudM.Domain.Entities.Post", "Post")
                        .WithMany("Saves")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("CloudM.Domain.Entities.PostTag", b =>
                {
                    b.HasOne("CloudM.Domain.Entities.Post", "Post")
                        .WithMany("Tags")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CloudM.Domain.Entities.Account", "TaggedAccount")
                        .WithMany("PostTags")
                        .HasForeignKey("TaggedAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("TaggedAccount");
                });

            modelBuilder.Entity("CloudM.Domain.Entities.Story", b =>
                {
                    b.HasOne("CloudM.Domain.Entities.Account", "Account")
                        .WithMany("Stories")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("CloudM.Domain.Entities.StoryHighlightGroup", b =>
                {
                    b.HasOne("CloudM.Domain.Entities.Account", "Account")
                        .WithMany("StoryHighlightGroups")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("CloudM.Domain.Entities.StoryHighlightItem", b =>
                {
                    b.HasOne("CloudM.Domain.Entities.StoryHighlightGroup", "StoryHighlightGroup")
                        .WithMany("Items")
                        .HasForeignKey("StoryHighlightGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CloudM.Domain.Entities.Story", "Story")
                        .WithMany("StoryHighlightItems")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Story");

                    b.Navigation("StoryHighlightGroup");
                });

            modelBuilder.Entity("CloudM.Domain.Entities.StoryView", b =>
                {
                    b.HasOne("CloudM.Domain.Entities.Story", "Story")
                        .WithMany("Views")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CloudM.Domain.Entities.Account", "ViewerAccount")
                        .WithMany("StoryViews")
                        .HasForeignKey("ViewerAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Story");

                    b.Navigation("ViewerAccount");
                });

            modelBuilder.Entity("CloudM.Domain.Entities.Account", b =>
                {
                    b.Navigation("BlocksInitiated");

                    b.Navigation("BlocksReceived");

                    b.Navigation("CommentReacts");

                    b.Navigation("Comments");

                    b.Navigation("Conversations");

                    b.Navigation("CreatedConversations");

                    b.Navigation("ExternalLogins");

                    b.Navigation("FollowRequestsReceived");

                    b.Navigation("FollowRequestsSent");

                    b.Navigation("Followers");

                    b.Navigation("Followings");

                    b.Navigation("Messages");

                    b.Navigation("NotificationReadState");

                    b.Navigation("OwnedConversations");

                    b.Navigation("PostReacts");

                    b.Navigation("PostSaves");

                    b.Navigation("PostTags");

                    b.Navigation("Posts");

                    b.Navigation("Settings")
                        .IsRequired();

                    b.Navigation("Stories");

                    b.Navigation("StoryHighlightGroups");

                    b.Navigation("StoryViews");
                });

            modelBuilder.Entity("CloudM.Domain.Entities.Comment", b =>
                {
                    b.Navigation("CommentReacts");

                    b.Navigation("Replies");
                });

            modelBuilder.Entity("CloudM.Domain.Entities.Conversation", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("CloudM.Domain.Entities.Message", b =>
                {
                    b.Navigation("HiddenBy");

                    b.Navigation("Medias");

                    b.Navigation("Reacts");
                });

            modelBuilder.Entity("CloudM.Domain.Entities.Notification", b =>
                {
                    b.Navigation("Contributions");
                });

            modelBuilder.Entity("CloudM.Domain.Entities.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Medias");

                    b.Navigation("Reacts");

                    b.Navigation("Saves");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("CloudM.Domain.Entities.Role", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("CloudM.Domain.Entities.Story", b =>
                {
                    b.Navigation("StoryHighlightItems");

                    b.Navigation("Views");
                });

            modelBuilder.Entity("CloudM.Domain.Entities.StoryHighlightGroup", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
